creat convert string to int in java output
We will do these in multiple ways.

Using Integer.parseInt() method:
The Integer.parseInt() method of the Integer class converts the string into its equivalent integer. It returns the string as a primitive int type. Syntax:

Integer.parseInt(String);
Where String is the given String you need to convert to int.

Java program to implement the Integer.parseInt() method:

Output:

Enter a numeric String to be converted to int:
-7788
After converting the String to int: -7788
Enter a numeric String to be converted to int:
16548
After converting the String to int: 16548
Enter a numeric String to be converted to int:
+394857483
After converting the String to int: 394857483
Enter a numeric String to be converted to int:
Hello
Please enter a string with only numeric characters.

java.lang.NumberFormatException: For input string: "Hello"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:652)
at java.lang.Integer.parseInt(Integer.java:770)
at StringtoInt.main(StringtoInt.java:11)
Enter a numeric String to be converted to int:
21474836477889
Please enter the numeric characters in the range of Integer (-2147483648 to 2147483647).

java.lang.NumberFormatException: For input string: "21474836477889"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:652)
at java.lang.Integer.parseInt(Integer.java:770)
at StringtoInt.main(StringtoInt.java:11)